name: Feature Request
description: Suggest a new feature or enhancement for Predoc
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: |
        I'm always frustrated when...
        It would be great if Predoc could...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      multiple: true
      options:
        - PDF Parser
        - Text Chunker
        - Embedding Model
        - Pipeline/Processor
        - API Endpoints
        - RabbitMQ/Task Queue
        - Storage (MinIO)
        - Vector DB (Milvus)
        - Configuration System
        - Docker/Deployment
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my use case)
        - High (significantly improves workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        For example:
        - I'm processing legal documents and need...
        - When running in production with 1000+ PDFs per hour...
        - For multilingual document processing...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: (Optional) Do you have ideas about how to implement this feature?
      placeholder: |
        If you have technical suggestions or would like to contribute:
        - Potential approaches
        - Libraries or tools that could help
        - API design proposals

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, examples, or references
      placeholder: Add any other context here (links to similar features, mockups, etc.)...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with Predoc's purpose (document preprocessing for RAG systems)
          required: true
        - label: I would be willing to contribute to implementing this feature (optional)
          required: false
